parqueadero/urls.py
from django.contrib import admin
from django.urls import path
from gestion import views
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp', views.emp),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]

gestion/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey

# Create your models here.
class Usuario(models.Model):
    idUsuario=models.PositiveSmallIntegerField(primary_key=True)
    cedula=models.CharField(max_length=10)
    nombre=models.CharField(max_length=50)
    apellido=models.CharField(max_length=50)
    celular=models.CharField(max_length=15)
    email=models.CharField(max_length=50)

    class Meta:  
        db_table = "usuario"  

    def nombre_completo(self):
        return "{}, {}".format(self.apellido, self.nombre)

    def __str__(self):
        return self.nombre_completo()

class Pago(models.Model):
    idPago=models.PositiveSmallIntegerField(primary_key=True)
    fecha=models.DateTimeField('date published')
    valor=models.FloatField()
    idUsuario=models.ForeignKey(
        Usuario, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        texto = "{} {}, {}"
        return texto.format(self.idUsuario,self.valor, self.fecha)

class Vehiculo(models.Model):
    idVehiculo=models.PositiveSmallIntegerField(primary_key=True)
    placa=models.CharField(max_length=6)
    color=models.CharField(max_length=10)
    marca=models.CharField(max_length=10)
    modelo=models.CharField(max_length=10)
    propietario=models.CharField(max_length=50)
    idUsuario=ForeignKey(
        Usuario, null=True, blank=True, on_delete=models.CASCADE)


    def caracteristica(self):
        return "{} {}, {}".format(self.placa, self.propietario, self.idVehiculo)

    def __str__(self):
        return self.caracteristica()

class Celda(models.Model):
    idCelda=models.PositiveSmallIntegerField(primary_key=True)
    dimensiones=models.CharField(max_length=50)
    idVehiculo=ForeignKey(
        Vehiculo, null=True, blank=True, on_delete=models.CASCADE)
    idUsuario=ForeignKey(
        Usuario, null=True, blank=True, on_delete=models.CASCADE)


    def __str__(self):
        texto = "{} {}, {}"
        return texto.format(self.idCelda, self.idVehiculo, self.idUsuario)

gestion/forms.py
from django import forms
from gestion.models import Usuario

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields= "__all__"
    

gestion/views.py
from django.shortcuts import render, redirect  
from gestion.forms import UsuarioForm
from gestion.models import Usuario
# Create your views here.  

def emp(request):  
    if request.method == "POST":  
        form = UsuarioForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = UsuarioForm()  
    return render(request,'index.html',{'form':form})  

def show(request):  
    usuarios= Usuario.objects.all()  
    return render(request,"show.html",{'usuarios': usuarios}) 

def edit(request, id):  
    usuario = Usuario.objects.get(id=id)  
    return render(request,'edit.html', {'usuario':usuario})  

def update(request, id):  
    usuario= Usuario.objects.get(id=id)  
    form = UsuarioForm(request.POST, instance = usuario)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'usuario': usuario})  
def destroy(request, id):  

    usuario = Usuario.objects.get(id=id)  
    usuario.delete()  
    return redirect("/show")  

gestion/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{usuario.idUsuario}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Usuario id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="idUsuario" id="id_idUsuario" required maxlength="20" value="{{ usuario.idUsuario }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Cedula Usuario:</label>  
    <div class="col-sm-4">  
        <input type="text" name="cedula" id="id_cedula" required maxlength="100" value="{{ usuario.cedula }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Nombre usuario:</label>  
    <div class="col-sm-4">  
        <input type="text" name="nombre" id="id_nombre" required maxlength="254" value="{{ usuario.nombre }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Apellido usuario:</label>  
    <div class="col-sm-4">  
        <input type="text" name="apellido" id="id_econtact" required maxlength="15" value="{{ usuario.apellido }}" />  
    </div>  
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Celular usuario:</label>  
    <div class="col-sm-4">  
        <input type="text" name="celular" id="id_celular" required maxlength="15" value="{{ usuario.celular }}" />  
    </div>  
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Email usuario:</label>  
    <div class="col-sm-4">  
        <input type="email" name="email" id="id_email" required maxlength="15" value="{{ usuario.email }}" />  
    </div>  
  </div>
    
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

gestion/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Usuario Id:</label>  
    <div class="col-sm-4">  
      {{ form.idUsuario }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Usuario Cedula:</label>  
    <div class="col-sm-4">  
      {{ form.cedula }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Usuario nombre:</label>  
    <div class="col-sm-4">  
      {{ form.nombre }}  
    </div>  
  </div> 
   </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Usuario apellido:</label>  
    <div class="col-sm-4">  
      {{ form.apellido }}  
    </div>  
  </div> 
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Usuario celular:</label>  
<div class="col-sm-4">  
  {{ form.celular }}  
</div>
  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Usuario email:</label>  
<div class="col-sm-4">  
  {{ form.email }}  
</div>  
  
</div>
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

gestion/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Usuario Records</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/> 

</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Usuario ID</th>  
        <th>Usuario Cedula</th>  
        <th>Usuario Nombre</th>  
        <th>Usuario Apellido</th> 
        <th>Usuario Celular</th> 
        <th>Usuario Email</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for usuario in usuarios %}  
    <tr>  
        <td>{{ usuario.idUsuario }}</td>  
        <td>{{ usuario.cedula }}</td>  
        <td>{{ usuario.nombre }}</td>  
        <td>{{ usuario.apellido }}</td> 
        <td>{{ usuario.celular }}</td> 
        <td>{{ usuario.email }}</td>     
        <td>   
            <a href="/edit/{{ usuario.idUsuario }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ usuario.idUsuario  }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  